version: "3.9"

services:
  promethai:
    networks:
      - agi_backend
    depends_on:
      - db_agi
      - redis
    build:
      context: ./
    volumes:
      - "./:/app"
    environment:
      - HOST=0.0.0.0
    profiles: ["exclude-from-up"] # Use `docker-compose run teenage-agi` to get an attached container
    ports:
      - 8000:8000
      - 443:443

  db_agi:
    image: postgres:14-alpine
    container_name: "agi_db"
    networks:
      - agi_backend
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: supersecreto
      POSTGRES_DB: agi_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis/redis-stack
    container_name: "redis"
    networks:
      - agi_backend
    ports:
      - "6379:6379"

networks:
  agi_backend:
    name: agi_backend
